# Generated by Django 5.2.7 on 2026-09-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок баннера')),
                ('subtitle', models.TextField(blank=True, verbose_name='Описание / Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Изображение баннера')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Ссылка при клике')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип (SVG/PNG)')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='Скидка от 0 до 100 процентов.', null=True, verbose_name='Скидка (%)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('color_code', models.CharField(blank=True, help_text='Например: #000000 для черного, #FFFFFF для белого', max_length=7, verbose_name='HEX-код цвета')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.brand', verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название серии / линейки')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL)')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('connector_from', models.CharField(choices=[('usb_a', 'USB-A'), ('usb_c', 'USB Type-C'), ('lightning', 'Lightning'), ('micro_usb', 'Micro-USB')], default='usb_c', max_length=20, verbose_name='Разъем 1 (откуда)')),
                ('connector_to', models.CharField(choices=[('usb_a', 'USB-A'), ('usb_c', 'USB Type-C'), ('lightning', 'Lightning'), ('micro_usb', 'Micro-USB')], default='usb_c', max_length=20, verbose_name='Разъем 2 (куда)')),
                ('length_m', models.DecimalField(decimal_places=2, help_text='Например: 0.25, 1.00, 2.00', max_digits=3, verbose_name='Длина кабеля (м)')),
                ('max_power_w', models.PositiveIntegerField(default=60, help_text='60, 100, 240', verbose_name='Макс. пропускаемая мощность (Вт)')),
                ('max_current_a', models.DecimalField(blank=True, decimal_places=1, help_text='3.0, 5.0', max_digits=3, null=True, verbose_name='Макс. ток (А)')),
                ('data_transfer_speed', models.CharField(blank=True, help_text='480 Мбит/с, 10 Гбит/с', max_length=50, null=True, verbose_name='Скорость передачи данных')),
                ('braiding_material', models.CharField(blank=True, help_text='Нейлоновая оплетка, Силикон, ТЭП', max_length=50, null=True, verbose_name='Материал оплетки')),
            ],
            options={
                'verbose_name': 'Кабель питания',
                'verbose_name_plural': 'Кабели питания',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('charger_type', models.CharField(choices=[('wall', 'Сетевое (в розетку)'), ('car', 'Автомобильное'), ('wireless', 'Беспроводная станция/док-станция')], default='wall', max_length=20, verbose_name='Тип зарядного')),
                ('max_power_w', models.PositiveIntegerField(help_text='Например: 20, 33, 65, 120', verbose_name='Максимальная мощность (Вт)')),
                ('usb_c_ports', models.PositiveSmallIntegerField(default=1, verbose_name='Портов USB Type-C')),
                ('usb_a_ports', models.PositiveSmallIntegerField(default=0, verbose_name='Портов USB-A')),
                ('is_gan', models.BooleanField(default=False, help_text='Компактный размер и меньший нагрев', verbose_name='GaN-технология')),
                ('fast_charging_protocols', models.CharField(blank=True, help_text='Power Delivery 3.0, Quick Charge 4.0, PPS', max_length=150, null=True, verbose_name='Протоколы быстрой зарядки')),
                ('has_cable_included', models.BooleanField(default=False, verbose_name='Кабель в комплекте')),
            ],
            options={
                'verbose_name': 'Зарядное устройство',
                'verbose_name_plural': 'Зарядные устройства',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('headphone_type', models.CharField(choices=[('tws', 'TWS (полностью беспроводные)'), ('in_ear', 'Вкладыши'), ('vacuum', 'Внутриканальные (вакуумные)'), ('on_ear', 'Накладные'), ('over_ear', 'Полноразмерные')], default='tws', max_length=20, verbose_name='Тип наушников')),
                ('connection_type', models.CharField(choices=[('wireless', 'Беспроводные'), ('wired', 'Проводные'), ('combined', 'Комбинированные (Bluetooth + кабель)')], default='wireless', max_length=20, verbose_name='Подключение')),
                ('has_anc', models.BooleanField(default=False, verbose_name='Активное шумоподавление (ANC)')),
                ('has_transparency_mode', models.BooleanField(default=False, verbose_name='Режим прозрачности')),
                ('audio_codecs', models.CharField(blank=True, help_text='SBC, AAC, aptX, LDAC', max_length=100, null=True, verbose_name='Поддерживаемые кодеки')),
                ('battery_life_hours', models.PositiveSmallIntegerField(blank=True, help_text='Например: 6', null=True, verbose_name='Время работы без кейса (ч)')),
                ('total_battery_life_hours', models.PositiveSmallIntegerField(blank=True, help_text='Например: 30', null=True, verbose_name='Время работы с кейсом (ч)')),
                ('has_wireless_charging_case', models.BooleanField(default=False, verbose_name='Беспроводная зарядка кейса')),
                ('bluetooth_version', models.CharField(blank=True, help_text='5.3, 5.4', max_length=20, null=True, verbose_name='Версия Bluetooth')),
                ('has_microphone', models.BooleanField(default=True, verbose_name='Наличие микрофона')),
                ('protection_class', models.CharField(blank=True, help_text='IPX4, IPX7', max_length=20, null=True, verbose_name='Класс влагозащиты')),
            ],
            options={
                'verbose_name': 'Наушники',
                'verbose_name_plural': 'Наушники',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('capacity_mah', models.PositiveIntegerField(help_text='Например: 10000, 20000, 30000', verbose_name='Емкость (мА·ч)')),
                ('max_power_w', models.PositiveIntegerField(default=22, help_text='Например: 22, 45, 65, 100', verbose_name='Макс. выходная мощность (Вт)')),
                ('usb_c_ports', models.PositiveSmallIntegerField(default=1, verbose_name='Выходов USB Type-C')),
                ('usb_a_ports', models.PositiveSmallIntegerField(default=1, verbose_name='Выходов USB-A')),
                ('has_wireless_charging', models.BooleanField(default=False, verbose_name='Беспроводная зарядка')),
                ('has_magsafe', models.BooleanField(default=False, verbose_name='Поддержка MagSafe / магнитное крепление')),
                ('has_built_in_cable', models.BooleanField(default=False, verbose_name='Встроенный кабель')),
                ('is_pass_through_supported', models.BooleanField(default=False, help_text='Зарядка повербанка и подключенных устройств одновременно', verbose_name='Сквозная зарядка')),
                ('display_type', models.CharField(choices=[('digital', 'Цифровой дисплей (%)'), ('led', 'Светодиодные индикаторы'), ('none', 'Отсутствует')], default='led', max_length=20, verbose_name='Индикация заряда')),
            ],
            options={
                'verbose_name': 'Повербанк',
                'verbose_name_plural': 'Повербанки',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('display_type', models.CharField(choices=[('amoled', 'AMOLED'), ('oled', 'OLED'), ('ips', 'IPS'), ('ltpo', 'LTPO OLED')], default='amoled', max_length=20, verbose_name='Тип матрицы')),
                ('display_size', models.DecimalField(decimal_places=1, help_text='Например: 6.7', max_digits=3, verbose_name='Диагональ (")')),
                ('display_resolution', models.CharField(blank=True, help_text='Например: 2400x1080', max_length=50, null=True, verbose_name='Разрешение')),
                ('display_refresh_rate', models.PositiveIntegerField(default=60, help_text='60, 90, 120, 144', verbose_name='Частота обновления (Гц)')),
                ('processor', models.CharField(blank=True, help_text='Snapdragon 8 Gen 3', max_length=100, null=True, verbose_name='Модель процессора')),
                ('gpu', models.CharField(blank=True, help_text='Adreno 750, Mali-G720', max_length=100, null=True, verbose_name='Графический процессор (GPU)')),
                ('core_count', models.PositiveSmallIntegerField(default=8, verbose_name='Количество ядер')),
                ('core_speed', models.CharField(blank=True, help_text='1x3.3 ГГц + 3x3.2 ГГц', max_length=100, null=True, verbose_name='Тактовая частота')),
                ('ram', models.PositiveIntegerField(help_text='Например: 8, 12, 16', verbose_name='ОЗУ (ГБ)')),
                ('storage', models.PositiveIntegerField(help_text='Например: 128, 256, 512, 1024', verbose_name='Встроенная память (ГБ)')),
                ('slot_config', models.CharField(choices=[('sim_only', 'Только SIM (без карты памяти)'), ('hybrid', 'Комбинированный (SIM или MicroSD)'), ('dedicated', 'Отдельный (2x SIM + MicroSD)'), ('no_physical', 'Только eSIM')], default='sim_only', max_length=20, verbose_name='Конфигурация слота')),
                ('max_sd_capacity', models.PositiveIntegerField(blank=True, help_text='Пусто, если SD не поддерживается', null=True, verbose_name='Макс. карта памяти (ГБ)')),
                ('main_camera_mp', models.PositiveIntegerField(help_text='Главный модуль для фильтров (например: 50)', verbose_name='Основная камера (Мп)')),
                ('main_camera_desc', models.CharField(blank=True, help_text='50 Мп + 12 Мп + 10 Мп', max_length=150, null=True, verbose_name='Полный блок камер')),
                ('front_camera_mp', models.PositiveIntegerField(blank=True, help_text='Например: 32', null=True, verbose_name='Фронтальная камера (Мп)')),
                ('max_video_resolution', models.CharField(choices=[('8k', '8K UHD (7680x4320)'), ('4k', '4K UHD (3840x2160)'), ('1080p', 'Full HD (1920x1080)'), ('720p', 'HD (1280x720)')], default='4k', max_length=20, verbose_name='Макс. разрешение видео')),
                ('optical_zoom', models.DecimalField(blank=True, decimal_places=1, help_text='Например: 3.0, 5.0, 10.0 (пусто, если нет)', max_digits=3, null=True, verbose_name='Оптический зум (x)')),
                ('battery_capacity', models.PositiveIntegerField(help_text='Например: 5000', verbose_name='Емкость аккумулятора (мАч)')),
                ('charging_power', models.PositiveIntegerField(blank=True, help_text='Например: 67', null=True, verbose_name='Мощность проводной зарядки (Вт)')),
                ('has_wireless_charging', models.BooleanField(default=False, verbose_name='Беспроводная зарядка')),
                ('has_reverse_charging', models.BooleanField(default=False, help_text='Зарядка других устройств (наушников/часов) от телефона', verbose_name='Реверсивная зарядка')),
                ('communication_standards', models.CharField(blank=True, help_text='2G, 3G, 4G, 5G', max_length=100, null=True, verbose_name='Стандарты связи')),
                ('sim_count', models.PositiveSmallIntegerField(default=2, verbose_name='Кол-во активных SIM')),
                ('has_esim', models.BooleanField(default=False, verbose_name='Поддержка eSIM')),
                ('usb_type', models.CharField(choices=[('type_c', 'USB Type-C'), ('lightning', 'Lightning'), ('micro_usb', 'Micro-USB')], default='type_c', max_length=20, verbose_name='Разъем зарядки')),
                ('nfc_support', models.BooleanField(default=False, verbose_name='Поддержка NFC')),
                ('has_jack_3_5', models.BooleanField(default=False, verbose_name='Разъем 3.5 мм')),
                ('wi_fi_standards', models.CharField(blank=True, help_text='Wi-Fi 6E, Wi-Fi 7', max_length=50, null=True, verbose_name='Wi-Fi')),
                ('bluetooth_version', models.CharField(blank=True, help_text='5.3, 5.4', max_length=20, null=True, verbose_name='Bluetooth')),
                ('operating_system', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Другая')], default='android', max_length=20, verbose_name='ОС')),
                ('os_version', models.CharField(blank=True, help_text='Android 14, iOS 17', max_length=30, null=True, verbose_name='Версия ОС')),
                ('protection_class', models.CharField(blank=True, help_text='IP68, IP54', max_length=30, null=True, verbose_name='Класс защиты')),
                ('material', models.CharField(blank=True, help_text='Стекло / металл', max_length=100, null=True, verbose_name='Материалы корпуса')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
            bases=('main.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выберите серию, к которой относится данный товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productgroup', verbose_name='Группа товаров'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d', verbose_name='Фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товара',
            },
        ),
    ]
