# Generated by Django 5.2.7 on 2026-08-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Емкость батареи'),
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия Bluetooth'),
        ),
        migrations.AddField(
            model_name='product',
            name='charging_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип зарядки'),
        ),
        migrations.AddField(
            model_name='product',
            name='communication_standards',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стандарты связи'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='main.product', verbose_name='Совместимо с устройствами'),
        ),
        migrations.AddField(
            model_name='product',
            name='core_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ядер процессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='core_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тактовая частота процессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_refresh_rate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Частота обновления дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрешение дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расширение памяти'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='interfaces_usb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Интерфейсы USB'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='navigational_systems',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Навигационные системы'),
        ),
        migrations.AddField(
            model_name='product',
            name='nfc_support',
            field=models.BooleanField(default=False, verbose_name='Поддержка NFC'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель процессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='protection_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс защиты'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_of_sim_cards',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество SIM-карт'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оперативная память (RAM)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sim_card_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип SIM-карты'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Встроенная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='wi_fi_standards',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стандарты Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен для заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.brand', verbose_name='Бренд'),
        ),
    ]
