# Generated by Django 5.2.7 on 2026-09-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('product_type', models.CharField(blank=True, choices=[('smartphone', 'Смартфоны'), ('headphone', 'Наушники'), ('charger', 'Зарядные устройства'), ('cable', 'Кабели'), ('powerbank', 'Повербанки')], help_text='Для верхнего уровня обязателен. У подкатегорий можно оставить пустым — тип будет унаследован.', max_length=20, verbose_name='Тип товара')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите одну или несколько подкатегорий. Верхние категории определяются типом товара.', related_name='product_groups', to='main.category', verbose_name='Подкатегории'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('product_type',), name='unique_root_category_product_type'),
        ),
    ]
