# Generated by Django 5.2.7 on 2026-08-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_alter_product_options_product_battery_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('length', models.CharField(blank=True, max_length=50, null=True, verbose_name='Длина кабеля')),
                ('connector_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='Разъем 1 (например, USB-A)')),
                ('connector_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Разъем 2 (например, Type-C)')),
            ],
            options={
                'verbose_name': 'Кабель питания',
                'verbose_name_plural': 'Кабели питания',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('power', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность (Вт)')),
                ('ports_count', models.PositiveIntegerField(default=1, verbose_name='Количество портов')),
                ('fast_charging', models.BooleanField(default=False, verbose_name='Поддержка быстрой зарядки')),
            ],
            options={
                'verbose_name': 'Зарядное устройство',
                'verbose_name_plural': 'Зарядные устройства',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип подключения (проводные/беспроводные)')),
                ('noise_cancellation', models.BooleanField(default=False, verbose_name='Активное шумоподавление (ANC)')),
                ('battery_life', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы от аккумулятора')),
            ],
            options={
                'verbose_name': 'Наушники',
                'verbose_name_plural': 'Наушники',
            },
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Емкость (мАч)')),
                ('ports_count', models.PositiveIntegerField(default=1, verbose_name='Количество портов')),
                ('fast_charging', models.BooleanField(default=False, verbose_name='Поддержка быстрой зарядки')),
            ],
            options={
                'verbose_name': 'Повербанк',
                'verbose_name_plural': 'Повербанки',
            },
            bases=('main.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_of_sim_cards',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='communication_standards',
        ),
        migrations.RemoveField(
            model_name='product',
            name='core_speed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_refresh_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='navigational_systems',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bluetooth_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wi_fi_standards',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='charging_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='core_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_resolution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sim_card_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_storage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protection_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interfaces_usb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nfc_support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compatible_with',
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('display_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип дисплея')),
                ('display_refresh_rate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Частота обновления дисплея')),
                ('display_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер дисплея')),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрешение дисплея')),
                ('communication_standards', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стандарты связи')),
                ('quantity_of_sim_cards', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество SIM-карт')),
                ('sim_card_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип SIM-карты')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Оперативная память (RAM)')),
                ('storage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Встроенная память')),
                ('extra_storage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Расширение памяти')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель процессора')),
                ('core_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ядер процессора')),
                ('core_speed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тактовая частота процессора')),
                ('battery_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Емкость батареи')),
                ('charging_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип зарядки')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система')),
                ('main_camera', models.CharField(blank=True, max_length=50, null=True, verbose_name='Основная камера')),
                ('front_camera', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фронтальная камера')),
                ('wi_fi_standards', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стандарты Wi-Fi')),
                ('bluetooth_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия Bluetooth')),
                ('nfc_support', models.BooleanField(default=False, verbose_name='Поддержка NFC')),
                ('navigational_systems', models.CharField(blank=True, max_length=100, null=True, verbose_name='Навигационные системы')),
                ('interfaces_usb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Интерфейсы USB')),
                ('protection_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс защиты')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал корпуса')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
            bases=('main.product',),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
