# Generated by Django 5.2.7 on 2026-08-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cable_charger_headphone_powerbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbank',
            name='power_output',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Выходная мощность (Вт)'),
        ),
    ]
