# Generated by Django 5.2.7 on 2026-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок баннера')),
                ('subtitle', models.TextField(blank=True, verbose_name='Описание / Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение баннера')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Ссылка при клике')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
