# Generated by Django 5.2.7 on 2026-08-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_powerbank_power_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headphone',
            name='battery_life',
        ),
        migrations.AddField(
            model_name='headphone',
            name='battery_autonomy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время автономной работы'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='battery_full_case_autonomy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время автономной работы с кейсом (для беспроводных)'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия Bluetooth (для беспроводных)'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='microphone',
            field=models.BooleanField(default=False, verbose_name='Наличие микрофона'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип наушников (вкладыши/накладные/полноразмерные)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
    ]
