# Generated by Django 5.2.7 on 2026-08-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_banner_delete_imagemodel_alter_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Изображение баннера'),
        ),
    ]
