# Generated by Django 5.2.7 on 2026-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='charging_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность зарядки'),
        ),
    ]
