# Generated by Django 5.2.7 on 2026-09-01 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_options_remove_product_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Samsung Galaxy S26 или Sony WH-CH720N', max_length=255, verbose_name='Название серии / линейки')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, help_text='Например: #000000 для черного, #FFFFFF для белого', max_length=7, verbose_name='HEX-код цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, help_text='Например: Black, White, Cobalt Violet', max_length=50, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выберите серию, к которой относится данный товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productgroup', verbose_name='Группа товаров'),
        ),
    ]
