# Generated by Django 5.2.7 on 2026-09-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productgroup_product_color_code_product_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_name',
        ),
    ]
