# Generated by Django 5.2.7 on 2026-09-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название серии / линейки'),
        ),
    ]
