# Generated by Django 5.2.7 on 2026-09-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productgroup_slug_alter_productgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип (SVG/PNG)'),
        ),
    ]
